### ISSUE TITLE
Infografia de Analisis del webbinar

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-1-infografia-luzm23-1#2]
[Infografia de Analisis del webbinar.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-luzm23-1/files/14285364/Infografia.de.Analisis.del.webbinar.pdf)

**Comment by Edwin14459** [comment]
**Calificación conforme a la rúbrica:**
1. Partes de la infografía: 4 puntos.
2. Coherencia y pertinencia: 3 puntos.
3. Organización de la información: 3 puntos.
4. Diseño de la infografía: 3 puntos.
5. Creatividad: 3 puntos.

Total=16/20
**CALIFICACIÓN=16**

_Buen trabajo, faltó agregar un poco de información y bibliografías._

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
